on:
  push:
    branches:
      - master
  release:
    types:
      - published

name: Asset Upload

jobs:
  build:
    name: Build and upload release assets
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux64, mac, windows32, windows64]
      fail-fast: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15
          java-package: jdk
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Determine Release
        if: contains(env.GITHUB_EVENT_NAME, 'ReleaseEvent')
        run: echo "USE_LAST_TAG=-Prelease.useLastTag=true" >> $GITHUB_ENV

      - name: Bundle distribution for ${{ matrix.platform }}
        run: ./gradlew $USE_LAST_TAG ${{ matrix.platform }}DistZip
      - name: Upload bundle for ${{ matrix.platform }}
        uses: actions/upload-release-asset@v1
        if: contains(env.GITHUB_EVENT_NAME, 'ReleaseEvent')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # This pulls from the RELEASE event this workflow was triggered by.
          # See https://developer.github.com/v3/activity/events/types/#releaseevent
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/distributions/TerasologyLauncher-${{ matrix.platform }}-${{ github.event.release.name }}.zip
          asset_name: TerasologyLauncher-${{ matrix.platform }}.zip
          asset_content_type: application/zip
